status: quietly ignore empty/missing logfile during analysis

diff --git a/status/status-common b/status/status-common
--- a/status/status-common
+++ b/status/status-common
@@ -1,5 +1,10 @@
+# -*- sh -*-
+
 check()
 {
+    # silently return if $log missing or empty
+    [ -s $log ] || return
+
     echo -n "Checking for '$*': "
     grep -q "$*" $log
     if [ $? -eq 0 ]; then
