net/check-gateway: skip single-ping ip_is_reachable() test
Using a single ping to verify reachability of the gateway in
ip_is_reachable() was never a good idea, because a single ping *can*
get lost here and there even on a good gateway.  Now that we're
relying on check-gateway (and have tons of logfiles to look at), it's
clearly causing some false-positives and unnecesary interface
swapping.

This commit removes the call to ip_is_reachable(), and dives straight
into ip_is_good_gw(), which uses pingenator to spam a bunch of hosts
(and returns successfully if it gets any replies from any of them).
If the gw is actually unreachable, ip_is_good_gw() works just fine and
doesn't take any longer.

The whole ip_is_reachable() thing is really a historical artifact,
first from before implementation of pingenator (the workhorse of
ip_is_good_gw()), then because we were initially only calling
pingenator if not --dry-run.  Once I'd established enough trust in
pingenator not leaving the system in a wonky state (it *does* add
potential routes to the system to test them), and enabled calling it
even when --dry-run, this just became a waste of code.

Juuuust in case I change my mind, I've left ip_is_reachable() in place
and put a big FIXME in there about the false-positives.  But we no
longer call it.

diff --git a/net/check-gateway b/net/check-gateway
--- a/net/check-gateway
+++ b/net/check-gateway
@@ -125,12 +125,23 @@ iface_get_devname()
 
 ip_is_reachable()
 {
+    # FIXME: need to make this better.  i'm seing quite a bit of
+    #        single-packet-test failures from otherwise functional
+    #        gateways... I suppose I should have seen that coming.
+    #
+    #        could alternatively just skip this test and just pound w/
+    #        pingenator...
+    #
     ping -w1 -c1 $1 >/dev/null 2>&1
 }
 
 
 # check to see if ip is a good gateway candidate.  pingenator will temporarily
 # use the ip as a gateway to ping a couple hosts to see if it REALLY works.
+#
+# NOTE: Pingenator will return success if it gets ANY responses.  We can tune
+#       that w/ --success PERCENT if needed, but for now that's fine.
+#
 ip_is_good_gw()
 {
     # FIXME: Should we include pingenator as a submodule of awesome-powers?  If
@@ -290,29 +301,20 @@ check_ifaces()
         r=($(echo $routes | tr ',' '\n'))
         decho checking ${r[1]}
 
-        # skip if not reachable
-        if ! ip_is_reachable ${r[1]}; then
-            # NOTE: My netgear 4g modem seems to need to have interface lowered
-            #       and reraised periodically... I thought this might get fixed
-            #       by letting NetworkManager auto-raise and track the
-            #       interface.  I seem to recall it auto-failing and
-            #       re-aquiring DHCP leases when this happens.  But, alas, I
-            #       keep seing unreachable gw IPs from the Netgear 4g
-            #       modem... and NetworkManager either doesn't notice or it's
-            #       taking way too long.  We'd better lower interfaces that
-            #       fail the reachable test.
+        # skip if not actually a usable gateway
+        #
+        # NOTE: We lower failed interfaces here so that subsequent runs will
+        #       attempt to re-raise them, hopefully returning functionality of
+        #       our preferred WAN interface automatically in case of a
+        #       temporary outage.
+        #
+        if ! ip_is_good_gw ${r[1]}; then
             if [ -n "$opt_dryrun" ]; then
-                echo "$(timestamp): Interface $iface's gw is not reachable, not lowering because --dry-run"
+                echo "$(timestamp): Interface $iface is not a good gateway, not lowering because --dry-run"
             else
-                echo "$(timestamp): Interface $iface's gw is not reachable, lowering"
+                echo "$(timestamp): Interface $iface is not a good gateway, lowering"
                 nmcli con down $iface >/dev/null 2>&1
             fi
-            continue
-        fi
-
-        # skip if not actually a usable gateway
-        if ! ip_is_good_gw ${r[1]}; then
-            decho "interface $iface not a good gateway, skipping"
             continue
         fi
 
