net/check-gateway: cli overhaul and --mail, v1
Haven't tested this yet at all... but should maybe work

diff --git a/net/check-gateway b/net/check-gateway
--- a/net/check-gateway
+++ b/net/check-gateway
@@ -6,9 +6,9 @@
 #
 # Licensed under the GPLv3. See the file COPYING for details. 
 #
-# Intended to be called periodically, checks that the system's default gateway
-# is reachable.  If it is NOT reachable, a secondary gateway is used as a
-# backup.  If it IS reachable, secondary gateway is removed.
+# Intended to be called periodically (every 10-15 seconds or so, perhaps once a
+# minute) to validate the system's default gateway or replace it with an
+# alternate one that is working.
 #
 # NOTE: All output appended to logfile, which is then mailed and removed each
 #       night (log rotation and mailing is not this script's responsibility).
@@ -20,46 +20,26 @@
 #        actually changes things (i.e., not --dry-run and usable gateways have
 #        changed).
 #
+#        Also, I'm not so sure we want to continue the daily noisy log email
+#        paradigm... I've stopped reading them because it takes too long, which
+#        makes them useless.  We should just send alert emails when problems
+#        happen.  Although... it can't hurt to be logging the snots out of
+#        things and emailing them to me nightly (instead of rotating).  I can
+#        always delete them out of my inbox.
+#
+# FIXME: Should our goal here be to ensure that we only have a functional
+#        gateway?  In other words, should we remove bad gateway even if there's
+#        not a good replacement... The only reason NOT to do this, is the
+#        occasional blib in connectivity that resolves itself within a couple
+#        minutes.  In this case, leaving things alone might be better.  That
+#        being said, if this script is getting called at a high frequency
+#        (every minute), removing the borky gateway will give better results
+#        (e.g., host unreachable instead of timing out) until it's back up.
+#
 
 
-usage()
-{
-    echo "usage: $(basename $0) [--help] [--verbose] [--dry-run] [--stdout]"
-    echo
-    echo "By default, output is appended to $log and is silent unless"
-    echo "something changes."
-}
-
-
-opt_dryrun=
-opt_verbose=
-opt_stdout=
-while [ $# -gt 0 ] ; do
-    case $1 in
-        --help)
-            usage
-            exit 0
-            ;;
-        -v|--verbose)
-            opt_verbose=1
-            ;;
-        -n|--dry-run)
-            opt_dryrun=1
-            ;;
-        --stdout)
-            opt_stdout=1
-            ;;
-        *)
-            echo "Unknown option or parameter \"$1\""
-            echo
-            usage
-            exit 1
-            ;;
-    esac
-
-    shift
-done
-
+log=$0.log
+lock=$0.lock
 
 
 # debug echo - only prints if enabled
@@ -337,6 +317,7 @@ check_ifaces()
             if [ -z "$(ip route show ${r[i]} via ${r[i+1]} dev $dev)" ]; then
                 # we're really modifying the routing table, clear out all
                 # managed routes first
+                gw_modified=y
                 remove_all_managed_routes $*
                 go="ip route add ${r[i]} via ${r[i+1]} dev $dev"
                 echo $(timestamp): $go
@@ -358,13 +339,91 @@ check_ifaces()
 }
 
 
+usage()
+{
+    if [ -n "$*" ]; then
+        echo ERROR: $*
+        echo
+    fi
+    echo "usage: $(basename $0) OPTIONS" #[--help] [--verbose] [--dry-run] [--stdout] [--mail MAILTO]"
+    echo
+    echo "  -h, --help                Show this help message and exit."
+    echo
+    echo "  -v, --verbose             Be verbose.  Default is silent unless routes need"
+    echo "                            to be modified."
+    echo
+    echo "  -n, --dry-run             Don't actually change anything, just print what"
+    echo "                            would be done."
+    echo
+    echo "  -s, --stdout              Log to stdout instead of the logfile.  Can't be used"
+    echo "                            w/ --mail."
+    echo
+    echo "  -m, --mail EMAILADDRESS   Email the logfile to EMAILADDRESS if the gateway is"
+    echo "                            modified.  Can't be used w/ --stdout."
+    echo
+    echo "By default, output is appended to $log and is silent unless"
+    echo "something changes.  If --mail specified, the logfile is also emailed to"
+    echo "EMAILADDRESS, but only if somthing is changed."
+}
 
 
+# call getopt
+#
+# NOTE: This handles spacing out arguments correctly for the case statement
+#       below and checks for unknown flags.  Required flags are checked for
+#       below.
+#
+# NOTE: The set -- command causes the resulting output of getopt to replace the
+#       current positional arguments (e.g, $1, $2).
+#
+__opts=$(getopt -un $0 \
+    -o hvnsm: \
+    --long help,verbose,dry-run,stdout,mail: -- $@)
+if [ $? != 0 ]; then
+    echo
+    usage
+    exit 1
+fi
+set -- $__opts
 
 
+opt_dryrun=
+opt_verbose=
+opt_stdout=
+opt_mail=
+# parse the new positional arguments
+while true; do
+    case "$1" in
+        -v|--verbose)
+            opt_verbose=y
+            shift 1
+            ;;
+        -n|--dry-run)
+            opt_dryrun=y
+            shift 1
+            ;;
+        -s|--stdout)
+            opt_stdout=y
+            opt_mail=
+            shift 1
+            ;;
+        -m|--mail)
+            opt_mail=$2
+            opt_stdout=
+            shift 2
+            ;;
+        --)
+            # done parsing
+            shift
+            break
+            ;;
+        *)
+            usage
+            exit 1
+            ;;
+    esac
+done
 
-log=$0.log
-lock=$0.lock
 
 # redirect all output to the logfile
 if [ -z "$opt_stdout" ]; then
@@ -388,6 +447,10 @@ fi
 decho "iface_list: $iface_list"
 
 # figure out path to pingenator
+#
+# FIXME: as soon as pingenator has an official release, replace this with a
+#        check in PATH and get rid of the pingenator submodule
+#
 pingenator=$(dirname $0)/../subprojects/pingenator/src/pingenator
 if [ ! -f $pingenator ]; then
     echo "ERROR: $pingenator not found"
@@ -405,7 +468,15 @@ go="touch $lock"
 decho $go
 deval $go
 
+gw_modified=
 check_ifaces $iface_list
+
+# If we actually changed something, mail results (if configured)
+if [ -n "$gw_modified" -a -n "$opt_mail" ]; then
+    mail -s "$(basename $0): gateway modified" $opt_mail -A $log
+    # FIXME: should we truncate the log once this is done?  I'm gonna go with
+    #        no until I'm 100% sure this is all working.
+fi
 
 go="rm -f $lock"
 decho $go
