net/check-gateway: troubleshooting empty dev errors, v2

diff --git a/net/check-gateway b/net/check-gateway
--- a/net/check-gateway
+++ b/net/check-gateway
@@ -112,7 +112,20 @@ iface_get_devname()
     #        IP-IFACE.  Eventually switch over, or maybe use IP-IFACE if
     #        non-empty otherwise DEVICES?
     #
-    nmcli con show $1 2>/dev/null |awk '/^GENERAL.DEVICES/ {print $NF}'
+    # NOTE: We do this nmcli lookup twice, because I've seen instances of it
+    #       returning empty even when the interface is up and good... but not
+    #       repeatably enough to pin down why.
+    #
+    dev=$(nmcli con show $1 2>/dev/null |awk '/^GENERAL.DEVICES/ {print $NF}')
+    if [ -z "$dev" ]; then
+        echo "$(timestamp): WARNING: dev empty, trying lookup again" 1>&2
+        dev=$(nmcli con show $1 2>/dev/null |awk '/^GENERAL.DEVICES/ {print $NF}')
+    fi
+    if [ -z "$dev" ]; then
+        echo "$(timestamp): ERROR: failed to lookup dev name" 1>&2
+        return
+    fi
+    echo $dev
 }
 
 
@@ -178,8 +191,17 @@ iface_remove_routes()
     iface=$1
 
     # get the device name
-    dev=$(iface_get_devname $iface)
-    # FIXME: check for empty dev
+    dev_k=${iface}_dev
+    dev=${!dev_k}
+    if [ -z "$dev" ]; then
+        echo "$(timestamp): WARNING: dev empty, trying lookup again (#3)"
+        dev=$(iface_get_devname $iface)
+    fi
+    if [ -z "$dev" ]; then
+        echo "$(timestamp): ERROR: failed to lookup dev name (#3)"
+        return
+    fi
+
     decho "looking up routes provided by $iface ($dev)"
     
     # figure out routes, first from manual config, then from nm info
@@ -259,7 +281,14 @@ check_ifaces()
 
         # get the device name
         dev=$(iface_get_devname $iface)
-        # FIXME: check for empty dev
+        if [ -z "$dev" ]; then
+            echo "$(timestamp): WARNING: failed to lookup dev for $iface, trying again"
+            dev=$(iface_get_devname $iface)
+        fi
+        if [ -z "$dev" ]; then
+            echo "$(timestamp): ERROR: failed to lookup dev for $iface, skipping"
+            continue
+        fi
         decho dev: $dev
         eval ${iface}_dev=$dev
 
@@ -440,10 +469,11 @@ set_gw()
     dev_k=${iface}_dev
     dev=${!dev_k}
     if [ -z "$dev" ]; then
-        echo "$(timestamp): WARNING: dev empty, trying lookup again"
+        echo "$(timestamp): WARNING: dev empty, trying lookup again (#2)"
         dev=$(iface_get_devname $iface)
-    elif [ -z "$dev" ]; then
-        echo "$(timestamp): ERROR: failed to lookup dev name"
+    fi
+    if [ -z "$dev" ]; then
+        echo "$(timestamp): ERROR: failed to lookup dev name (#2)"
         return
     fi
     routes_k=${iface}_routes
