systemd: overhauled the wait-online services
Looks like I never actually finished this from the initial commit.
Oops.  In addition to actually connecting the dots to make working
services (w/ comments regarding what/why we're doing), I made the
wait-for-host script accept multiple hosts to wait on.

diff --git a/net/wait-for-host b/net/wait-for-host
--- a/net/wait-for-host
+++ b/net/wait-for-host
@@ -1,9 +1,17 @@
 #!/bin/bash
 
-timeout=15
-for x in $(seq $timeout); do
-    ping -c1 -W1 $1 && exit 0
-    sleep 1
+while [ $# -gt 0 ]; do
+    timeout=15
+    while [ $timeout -gt 0 ]; do
+        ping -c1 -W1 $1 && break
+        sleep 1
+        timeout=$((timeout-1))
+    done
+    if [ $timeout -eq 0 ]; then
+        echo "Waiting for $1 failed after 15 seconds!"
+        exit 1
+    fi
+    shift
 done
 
-exit 1
+exit 0
